function [axh64,npix,texth1,texth2] = CreateRecordingWindow(windY)
%  [axh,texth1,texth2] = CreateRecordingWindow(windY)
% Set up the GUI window interface for recording a single file
% windY: a 64 by 2 matrix giving the y-axis scaling for each plot
% axh: a 64-vector of handles to the axes
% npix: the number of pixels along the x-axis (also the x range)
% texth1,texth2: handles to two text objects in the window
rwh = findobj(0,'Tag','RecWindow');
if (~isempty(rwh))
	% This doesn't appear to ever get called...
	'Redoing...'
	figure(rwh)
	axh64 = flipdim(findobj(rwh,'Type','axes')',2);
	npix = get(axh64(1),'UserData');
	texth1 = findobj(rwh,'Tag','TextTotTime');
	texth2 = findobj(rwh,'Tag','TextTimeLeft');
	patchH = findobj(rwh,'Type','patch');
	for i = 1:64
		axes(axh64(i));
		axis([1,npix,windY(i,1),windY(i,2)]);
	end
	delete(patchH)
	drawnow
	return
else
	[axh64,npix64] = CreateAxes64;
	npix64 = floor(npix64);
	npix = npix64(1);			% All the values are the same
	for i = 1:64
		axes(axh64(i));
		axis([1,npix,windY(i,1),windY(i,2)]);
		axis manual
		hold on
	end
	figsize = get(gcf,'Position');
	buttonbottom = figsize(4)-35;
	h1 = uicontrol('Parent',gcf, ...
		'Units','points', ...
		'Position',[50 buttonbottom 76 25], ...
		'Callback','RecWindowCallback start', ...
		'String','Start', ...
		'Enable','on', ...
		'Tag','StartRecButton');
	h1 = uicontrol('Parent',gcf, ...
		'Units','points', ...
		'Position',[175 buttonbottom 76 25], ...
		'Callback','RecWindowCallback stop', ...
		'String','Stop', ...
		'Enable','off', ...
		'Tag','StopRecButton');
	texth1 = uicontrol('Parent',gcf, ...
		'Units','points', ...
		'Position',[426 buttonbottom 199 25], ...
		'Style','text', ...
		'Tag','TextTotTime');
	texth2 = uicontrol('Parent',gcf, ...
		'Units','points', ...
		'Position',[727 buttonbottom 199 25], ...
		'Style','text', ...
		'Tag','TextTimeLeft');
end
