function fig = AutoCorrFig(t,trange,units)
% AutoCorrFig: interactively view the autocorrelation for a spike train
% AutoCorrFig(t,tmax,units), where
%    t is the vector of spike times
%    tmax is the largest time separation to consider
%    units is a string giving the name of the units in which time is measured
%		(blank if omitted)
if (nargin < 3)
	units = '';
end
w = 234;
h = 182;
ploc = get(0,'PointerLocation');
hfig = figure('Units','points', ...
	'Color',[0.8 0.8 0.8], ...
	'Position',[ploc(1)-3,ploc(2)-h-10,w,h], ...
	'Tag','Fig1');
h1 = axes('Parent',hfig, ...
	'Units','pixels', ...
	'CameraUpVector',[0 1 0], ...
	'CameraUpVectorMode','manual', ...
	'Color',[1 1 1], ...
	'Position',[49 69 163 99], ...
	'Tag','ACAxes', ...
	'XColor',[0 0 0], ...
	'YColor',[0 0 0], ...
	'ZColor',[0 0 0]);
h2 = text('Parent',h1, ...
	'Color',[0 0 0], ...
	'HandleVisibility','off', ...
	'HorizontalAlignment','center', ...
	'Position',[0.4938271604938271 -0.1734693877551019 9.160254037844386], ...
	'Tag','XLabelStr', ...
	'String',['Time (',units,')'], ...
	'VerticalAlignment','cap');
set(get(h2,'Parent'),'XLabel',h2);
h2 = text('Parent',h1, ...
	'Color',[0 0 0], ...
	'HandleVisibility','off', ...
	'HorizontalAlignment','center', ...
	'Position',[-0.1419753086419753 0.489795918367347 9.160254037844386], ...
	'Rotation',90, ...
	'Tag','YLabelStr', ...
	'String','#/bin',...
	'VerticalAlignment','baseline');
set(get(h2,'Parent'),'YLabel',h2);
h1 = uicontrol('Parent',hfig, ...
	'Units','points', ...
	'Position',[48 14.5 90 14], ...
	'String',['Time range (',units,'):'], ...
	'Style','text', ...
	'Tag','StaticText1');
hedit = uicontrol('Parent',hfig, ...
	'Units','points', ...
	'BackgroundColor',[1 1 1], ...
	'Position',[135 11 76 22], ...
	'Style','edit', ...
	'String',num2str(trange), ...
	'HorizontalAlignment','right', ...
	'Callback','AutoCorrFigCallback replot',...
	'Tag','EditText1');
setappdata(hfig,'t',t);
setappdata(hfig,'textunits',units);
AutoCorrFigCallback('replot',hedit,hfig);
if nargout > 0, fig = hfig; end
