#!/usr/bin/env bash
# Install mex code files
#    This code identifies c and c++ source codes in spike-sorting directory(and subdirectories),
#    and compiles to mex code. 
#   
# usage:
#    run ./installmexfiles in the `spike-sorting/matlab` folder
#    runs with compile_mex.m mcode.
#    check if compile_mex.m mcode is in the same folder.
#
# custom variables: 
#    MEXCODESDIR
#    -----------
#       name of the directory. copy c and c++ source codes to `MEXCODESDIR` folder
#
#    COMPILE
#    -------
#       m-code name. (default: compile_mex.m)
#
#    MATLAB
#    ------
#       matlab executable file.
#

# ***** Setting custom variables ***** #
# mex codes dir, and compile matlab code, and matlab executable.
MEXCODESDIR="mexcodes"
COMPILE="compile_mex.m"
if [ "$(hostname)" == 'sni-vcs-baccus.stanford.edu' ]; then
  MATLAB="/share/software/MATLAB-R2014b/bin/matlab"
elif [ "$(hostname)" == 'lane.local' ]; then
  MATLAB="/Applications/MATLAB_R2012a_Student.app/bin/matlab"
else
  MATLAB="/Applications/MATLAB_R2014a.app/bin/matlab"
fi
# ************************************ #

if [ ! -f "$COMPILE" ]; then
    echo "[Error] file $COMPILE not found.
          Need to have m-code(compile_mex.m) in the same directory to compile mex codes.
          Check if the m-code name is assigned to COMPILE variable correctly."
    exit 1
fi
if [ ! -f "$MATLAB" ]; then
    echo "[Error] Incorrect matlab path: $MATLAB not found.
          Set the matlab executable file path correctly to the MATLAB variable."
    exit 1
fi



set -eu

start_message() {
    echo
    echo "Install mex codes..."
    echo
}


display_help() {
    echo
    echo "[HELP] installmexfiles"
    echo "  usage: ./installmexfiles [OPTION]"
    echo
    echo "  Run this code in the spike-sorting/matlab folder of GroupCW

  description: Install mex code files
     This code identifies c and c++ source codes in spike-sorting directory(and subdirectories),
     and compiles to mex code. 
    
  usage:
     run ./installmexfiles in the spike-sorting/matlab folder
     runs with compile_mex.m mcode.
     check if compile_mex.m mcode is in the same folder.
 
  custom variables: 
     MEXCODESDIR
     -----------
        name of the directory. copy c and c++ source codes to MEXCODESDIR folder
 
     COMPILE
     -------
        m-code name. (default: compile_mex.m)
 
     MATLAB
     ------
        matlab executable file."
    echo
    echo "  -h, --help         print a help message, menu and usage."
    echo "  -v, --verbose      print verbose output."
    echo "  -g, --debug        print verbose output."
    exit 1
}

# find all source codes and header files
find_all() {
    if [ $# -eq 1 ]; then
        currdir=$1
        find $currdir -iname "*.c*" -o -iname "*.h*"
    else
        find . -iname "*.c*" -o -iname "*.h*"
    fi
}

# find source codes only (c and c++ codes)
find_source_codes() {

    if [ $# -eq 1 ]; then
        currdir=$1
        find $currdir -iname "*.c" -o -iname "*.cpp"
    else
        find . -iname "*.c" -o -iname "*.cpp"
    fi
}

DEBUGMODE=FALSE
VFLAG=FALSE
# check usage of the shell script.
if [ $# -gt 0 ]; then
    OPTION=$1
    case "$OPTION" in
        -h | --help) display_help;;
    #--help) display_help;;
        -v) VFLAG=TRUE;;
        --verbose) VFLAG=TRUE;;
        -g) DEBUGMODE=TRUE;;
    esac
else
    start_message
fi

# current dir path
currdir=$PWD

# make mexcodes dir, copy source codes into mexcodes dir.
mkdir -p $MEXCODESDIR
for file in $(find_all $currdir); do
    filefullname=${file##*/}
    if [ -f "$MEXCODESDIR/$filefullname" ]
    then
        if [ $VFLAG = TRUE ];then
            echo "$filefullname in $MEXCODESDIR folder... not copied"
        fi
    else
        if [ $VFLAG = TRUE ];then
            echo "$filefullname not in $MEXCODESDIR folder... copied $filefullname to $MEXCODESDIR folder"
        fi
        cp $file ./$MEXCODESDIR/
    fi
done

# copy compile.m matlab code to mexcodes dir
cp $COMPILE ./$MEXCODESDIR/
cd $MEXCODESDIR

# run matlab, compile source codes into mex files
$MATLAB -nodisplay -nosplash -nodesktop -nojvm -r "debugmode='$DEBUGMODE'; ${COMPILE%.*}" $MEXCODESDIR #| tail -n 3

# delete compile.m matlab file and source files
rm -f $COMPILE
for file in $(find_all); do
    filefullname=${file##*/}
    if [ -f "$filefullname" ]
    then
        if [ $VFLAG = TRUE ];then
            echo "$filefullname in $MEXCODESDIR deleted..."
        fi
        rm -f $filefullname
    fi
done

# copy compiled mex codes to the original source locations
for file in $(ls); do
    echo
    filename=${file%.*}
    
    for locs in $(find_source_codes $currdir | grep $filename); do
        fileloc=${locs%/*}
        cp $file $fileloc
        if [ $VFLAG = TRUE ];then
            echo "copied $file to $fileloc"
        fi
    done
done

cd $currdir 
rm -rf $MEXCODESDIR


