function fig = ClusterSpikeWfms(spikefiles,ctfiles,channels,snipindx,multiindx,f,t,proj,clustnums,polygons,hsort)
% Compute their projections on the filters
hfig = Cluster(proj(2,:),proj(1,:));
h1 = uicontrol('Parent',hfig, ...
'Units','points', ...
'Position',[412 337 76 30], ...
'String','AutoCorr',...
'Callback','ClustSWCallback AutoCorr',...
'Tag','AutoCorrButton');
h1 = uicontrol('Parent',hfig, ...
'Units','points', ...
'Position',[412 298 76 30], ...
'String','Waveforms',...
'Callback','ClustSWCallback Waveforms',...
'Tag','WaveformsButton');
hclustmodebox = uicontrol('Parent',hfig, ...
'Units','points', ...
'Position',[425 20 111 25], ...
'String','Draw polygon', ...
'Style','checkbox', ...
'Callback','ClustSWCallback Clustmodebox',...
'Tag','clustmode', ...
'Value',getuprop(hsort,'clustmode'));
setuprop (hfig,'hsort',hsort);
setuprop(hfig,'t',t);
setuprop(hfig,'f',f);
setuprop(hfig,'ctfiles',ctfiles);
setuprop(hfig,'spikefiles',spikefiles);
setuprop(hfig,'channels',channels);
setuprop(hfig,'snipindx',snipindx);
setuprop(hfig,'multiindx',multiindx);
if (nargin > 4)
	% Co-opt the "Clear" function and turn it into a "Revert" function
	h = findobj(hfig,'Tag','ClearButton');
	set(h,'String','Revert','Callback','ClustSPCallback Revert');
	setuprop(hfig,'clustnums0',clustnums);
	setuprop(hfig,'polygons0',polygons);
	ClustSPCallback('Revert',hfig);
end
if nargout > 0, fig = hfig; end
