function cthandle = crosstalkwindow (hsort,g);
snipsize=[-6 20];
numch=size(g.channels,2);
%open figure
figure ('Name','Crosstalk','Position', [300 50 750 750]);%,'doublebuffer','on');

% number of white boxes in array window
if strcmp(g.array, 'hidens')
    visiblechannels = numch;
    xsize = 1/14;
    ysize = 1/13;
else
    visiblechannels = 63;
    xsize = 0.11;
    ysize = 0.11;
end

%Create axis for each channel
for chan= 0:visiblechannels
	pos=GetPosition(chan, g.array);
	axes('position',[pos xsize ysize]);
	set(gca,'XTickLabel',{''},'xtick',[],'YTickLabel',{''},'Ytick',[],'XColor',[0.8 0.8 0.8],'YColor',[0.8 0.8 0.8]);
end
for chindx=1:numch
	pos=GetPosition(g.channels(chindx), g.array);
	axes('position',[pos xsize ysize]);
	hcc(chindx)=gca;	
end
h1 = uicontrol('Parent',gcf, ...
'Units','points', ...
'Position',[30 40 100 29], ...
'String','Show all', ...
'Callback','crosstalkfunctions showall',...
'Tag','');
h1 = uicontrol('Parent',gcf, ...
'Units','points', ...
'Position',[30 5 100 29], ...
'String','Show mean', ...
'Callback','crosstalkfunctions showmean',...
'Tag','');
h1 = uicontrol('Parent',gcf, ...
'Units','points', ...
'Position',[650 40 122 29], ...
'String','Sort crosstalk', ...
'Callback','crosstalkfunctions sortcrosstalk',...
'Tag','');
h1 = uicontrol('Parent',gcf, ...
'Units','points', ...
'Position',[650 5 122 29], ...
'String','Mark for removal', ...
'Callback','crosstalkfunctions remove',...
'Tag','');

%Handles for figure and all axes
handles=getappdata (hsort,'handles');
handles.cc=hcc;
handles.sort=hsort;
setappdata (gcf,'g',g);
setappdata (gcf,'handles',handles);
cthandle=gcf;



