function fig = Crosstalkremove(spikefiles,outfile,time,channel,params)
% CrossTalk: sort spikes by their appearance on multiple electrodes
% fig = CrossTalk(spikefiles,outfile,channels,params)
% 	spikefiles: a cell array of spike file names OR
%		the name of a .mat file with peak,time information already saved
%	outfile: name of file in which to store cell definitions and remaining (unsorted)
%		spikes
%	channels (optional): a vector of channel numbers
%	params (optional): a structure which contains the constants controlling
%		default behavior. See CTDefParams.m for the default values
if (nargin < 5)
	if (nargin < 4)
		params = [];
		channels = 'all';
	else
		if (isstruct(channels))
			params = channels;
			channels = 'all';
		else
			params = [];
		end
	end
end
params = CTDefParams(params);	% Fill in any blank fields with defaults


chans = GetSnipNums(spikefiles);

if (strcmp(channels,'all'))
	channels = chans;
end
channels0 = channels;
[channels,chindx] = intersect(chans,channels);


keyboard
fracspikes=1;
hfig = figure('Units','points', ...
	'Color',[0.8 0.8 0.8], ...
	'Position',[21 92 963 603], ...
	'ButtonDownFcn','CTremovefunctions Unselect',...
	'KeyPressFcn','CTremovefunctions KeyTrap',...
	'Name','CrossTalk Grouping',...
	'Tag','CrossTalkFig');
for i = 1:4
	for j = 1:8
		left = 15+(j-1)*120;
		if (i > 2)
			bottom = 451-(i-1)*100;	% was 451
		else
			bottom = 501-(i-1)*100;	% was 481
		end
		pos = [left,bottom,109,91];
		if (i > 2)
			i1 = i-2;
			i2 = j+8;
		else
			i1 = i;
			i2 = j;
		end
		haxc(i1,i2) = axes('Parent',hfig, ...
			'Units','pixels', ...
			'CameraUpVector',[0 1 0], ...
			'Color',[1 1 1], ...
			'Position',pos, ...
			'XColor',[0 0 0], ...
			'YColor',[0 0 0], ...
			'ZColor',[0 0 0]);
	end
end
for i = 1:8
	for j = 1:2
		left = 15+(i-1)*120;
		bottom = 370-(j-1)*250;	%350-(j-1)*230;
		pos = [left bottom 109 20];
		hctext(i+(j-1)*8) = uicontrol('Parent',hfig, ...
			'Units','points', ...
			'Position',pos, ...
			'String','0 vs 0: 0', ...
			'Style','text', ...
			'Tag','ClusterText');
	end
end
	
h1 = uicontrol('Parent',hfig, ...
	'Units','points', ...
	'Position',[30 70 82 29], ...
	'String','Cluster', ...
	'Callback','CTremovefunctions Cluster',...
	'Enable','off',...
	'Tag','ClusterButton');
h1 = uicontrol('Parent',hfig, ...
	'Units','points', ...
	'HorizontalAlignment','left', ...
	'Position',[130 70 50 20], ...
	'String','block size', ...
	'Style','text', ...
	'Tag','BlockSizeText');
h1 = uicontrol('Parent',hfig, ...
	'Units','points', ...
	'BackgroundColor',[1 1 1], ...
	'Position',[190 73 61 21], ...
	'HorizontalAlignment','right', ...
	'String',num2str(params.BlockSize), ...
	'Style','edit', ...
	'Tag','BlockSize');
h1 = uicontrol('Parent',hfig, ...
	'Units','points', ...
	'Position',[30 30 82 29], ...
	'String','KillMode', ...
	'Callback','CTremovefunctions KillMode',...
	'Tag','KillModeButton');

h1 = uicontrol('Parent',hfig, ...
	'Units','points', ...
	'HorizontalAlignment','left', ...
	'Position',[330 70 75 20], ...
	'String','Close:', ...
	'Style','text', ...
	'Tag','StaticText4');
h1 = uicontrol('Parent',hfig, ...
	'Units','points', ...
	'BackgroundColor',[1 1 1], ...
	'HorizontalAlignment','right', ...
	'Position',[410 73 49 20], ...
	'String',num2str(params.TPlot), ...
	'Style','edit', ...
	'Callback','CTremovefunctions RecalculatePairs,CTremovefunctions(''UpdateDisplay'',gcbf)',...
	'Tag','TPlot');
h1 = uicontrol('Parent',hfig, ...
	'Units','points', ...
	'Position',[460 70 12 20], ...
	'String','s', ...
	'Style','text', ...
	'Tag','StaticText4');
h1 = uicontrol('Parent',hfig, ...
	'Units','points', ...
	'HorizontalAlignment','left', ...
	'Position',[330 40 75 20], ...
	'String','Simultaneous:', ...
	'Style','text', ...
	'Tag','StaticText4');
h1 = uicontrol('Parent',hfig, ...
	'Units','points', ...
	'BackgroundColor',[1 1 1], ...
	'HorizontalAlignment','right', ...
	'Position',[410 43 49 20], ...
	'String',num2str(params.TSimult), ...
	'Style','edit', ...
	'Callback','CTremovefunctions(''UpdateDisplay'',gcbf)',...
	'Tag','TSimult');
h1 = uicontrol('Parent',hfig, ...
	'Units','points', ...
	'Position',[460 40 12 20], ...
	'String','s', ...
	'Style','text', ...
	'Tag','StaticText4');
h1 = uicontrol('Parent',hfig, ...
	'Units','points', ...
	'Position',[500 70 82 29], ...
	'String','Prev', ...
	'Callback','CTremovefunctions Prev',...
	'Enable','off',...
	'Tag','PrevButton');
h1 = uicontrol('Parent',hfig, ...
	'Units','points', ...
	'Position',[600 70 82 29], ...
	'String','Next', ...
	'Callback','CTremovefunctions Next',...
	'Tag','NextButton');
h1 = uicontrol('Parent',hfig, ...
	'Units','points', ...
	'Position',[550 30 82 29], ...
	'String','To Start', ...
	'Enable','off',...
	'Callback','CTremovefunctions Start',...
	'Tag','StartButton');
h1 = uicontrol('Parent',hfig, ...
	'Units','points', ...
	'HorizontalAlignment','right', ...
	'Position',[690 70 50 20], ...
	'String','', ...
	'Style','text', ...
	'Tag','PageText');

h1 = uicontrol('Parent',hfig, ...
	'Units','points', ...
	'Position',[740 20 82 29], ...
	'String','Cancel', ...
	'Callback','CTremovefunctions Cancel',...
	'Tag','CancelButton');
h1 = uicontrol('Parent',hfig, ...
	'Units','points', ...
	'Position',[850 20 82 29], ...
	'String','Done', ...
	'Callback','CTremovefunctions Done',...
	'Tag','DoneButton');
% Set the data that the callbacks will need
setappdata(hfig,'params',params);
setappdata(hfig,'SpikeFiles',spikefiles);
setappdata(hfig,'CellDefFile',outfile);
setappdata(hfig,'channels',channels);
setappdata(hfig,'haxc',haxc);
setappdata(hfig,'hctext',hctext);
setappdata(hfig,'time',time);
%setappdata(hfig,'peak',peak);
setappdata(hfig,'pairtime',{});
setappdata(hfig,'fracspikes',fracspikes);
setappdata(hfig,'ShowRange',[1 16]);
setappdata(hfig,'KillMode',0);
CTremovefunctions('RecalculatePairs',hfig);
CTremovefunctions('UpdateDisplay',hfig);
%CTremovefunctions('SetCAxProp',hfig);
if nargout > 0, fig = hfig; end

