function fig = DoMultiChannel(hmain,g,sortchannels)
% DoMultiChannel: group one electrode's spike waveforms based on shape
% DoMultiChannel(hmain,g,sortchannels)

if (g.pwflag)
	nfiles=1;
	nchans=63;
	global sptimes
	chindices=sortchannels;
	for ch=1:63
		nsnips(ch,1)=length(sptimes{ch}{1});
	end
	rectime(1)=max(sptimes{ch}{1}(1,:)');
else
	chansrec=intersect(g.channels,sortchannels);
	if (chansrec~=sort(sortchannels))		% Was this channel recorded?
		fig = [];
		errordlg(sprintf('These channels were not recorded: %d',setdiff(sortchannels,g.channels)));
		return;
	end
	nchans=length(sortchannels);
	nfiles=length(g.spikefiles);
	for ch=1:nchans
		chindices(ch)=find(sortchannels(ch)==g.channels);
	end
	for fnum= 1:nfiles
		[fid,message] = fopen(g.spikefiles{fnum},'r');
		header{fnum} = ReadSnipHeader(fid);
		scanrate(fnum) = header{fnum}.scanrate;
		rectime(fnum) = header{fnum}.nscans/header{fnum}.scanrate;
	end
end
%Get times of spikes on first channel and coincident spikes on other channels
[sptimes,spindx]= Multiindex (hmain,g,sortchannels,chindices);
hfig = figure('Units','points', ...
'Color',[0.8 0.8 0.8], ...
'Position',[21 92 963 603], ...
'ButtonDownFcn','DoMultiChanFunctions Unselect',...
'KeyPressFcn','DoMultiChanFunctions KeyTrap',...
'Name','Channel Grouping',...
'Tag','ChannelFig','doublebuffer','on','NumberTitle','off');
for i = 1:3
	for j = 1:7
		if (j > 1)
			left = 144+(j-2)*120;
		else
			left = 15;
		end
		if (i==1)
			bottom = 471; height=90;
		elseif (i==2)
			bottom = 390; height=80;
		else
			bottom = 325; height=64;
		end
		pos = [left,bottom,109,height];
		haxc(i,j) = axes('Parent',hfig, ...
		'Units','pixels', ...
		'CameraUpVector',[0 1 0], ...
		'Color',[1 1 1], ...
		'Position',pos, ...
		'XColor',[0 0 0], ...
		'YColor',[0 0 0], ...
		'ZColor',[0 0 0]);
	end
end
params = DCDefParams([]);
if (g.pwflag)
	h1 = uicontrol('Parent',hfig, ...
	'Units','points', ...
	'HorizontalAlignment','left', ...
	'Position',[859 505 42 19], ...
	'String','Width', ...
	'Style','text', ...
	'Tag','StaticText3');
else
	h1 = uicontrol('Parent',hfig, ...
	'Units','points', ...
	'HorizontalAlignment','left', ...
	'Position',[859 505 42 19], ...
	'String','Display', ...
	'Style','text', ...
	'Tag','StaticText3');
	h1 = uicontrol('Parent',hfig, ...
	'Units','points', ...
	'HorizontalAlignment','right', ...
	'Position',[140 140 30 20], ...
	'String','noise', ...
	'Style','text', ...
	'Tag','StaticText1');
	h1 = uicontrol('Parent',hfig, ...
	'Units','points', ...
	'BackgroundColor',[1 1 1], ...
	'Position',[180 180 61 21], ...
	'String',num2str(params.NSpikes), ...
	'Style','edit', ...
	'Tag','NumSpikes');
	h1 = uicontrol('Parent',hfig, ...
	'Units','points', ...
	'BackgroundColor',[1 1 1], ...
	'Position',[180 140 61 21], ...
	'String',num2str(params.NNoise), ...
	'Style','edit', ...
	'Tag','NumNoise');
	h1 = uicontrol('Parent',hfig, ...
	'Units','points', ...
	'Position',[30 180 102 29], ...
	'String','Variance Filters', ...
	'Callback','DoMultiChanFunctions BuildFilters',...
	'Tag','BuildFiltersButton');
	h1 = uicontrol('Parent',hfig, ...
	'Units','points', ...
	'Position',[30 140 102 29], ...
	'String','Discrim. Filters', ...
	'Callback','DoMultiChanFunctions DiscrimFilters',...
	'Enable','off', ...
	'Tag','DiscrimFiltersButton');
	h1 = axes('Parent',hfig, ...
	'Units','pixels', ...
	'CameraUpVector',[0 1 0], ...
	'Color',[1 1 1], ...
	'Position',[291 201 180 95], ...
	'Tag','SVAxes', ...
	'XColor',[0 0 0], ...
	'YColor',[0 0 0], ...
	'ZColor',[0 0 0]);
	ylabel('Singular values');
	h1 = axes('Parent',hfig, ...
	'Units','pixels', ...
	'CameraUpVector',[0 1 0], ...
	'Color',[1 1 1], ...
	'Position',[521 201 180 95], ...
	'Tag','WaveAxes', ...
	'XColor',[0 0 0], ...
	'YColor',[0 0 0], ...
	'ZColor',[0 0 0]);
	ylabel('Waveforms');
	h1 = axes('Parent',hfig, ...
	'Units','pixels', ...
	'CameraUpVector',[0 1 0], ...
	'Color',[1 1 1], ...
	'Position',[751 201 180 95], ...
	'Tag','FiltAxes', ...
	'XColor',[0 0 0], ...
	'YColor',[0 0 0], ...
	'ZColor',[0 0 0]);
	ylabel('Filters');
	h1 = uicontrol('Parent',hfig, ...
	'Units','points', ...
	'Position',[30 270 82 29], ...
	'String','Sort Subset', ...
	'Callback','DoMultiChanFunctions SortSubset',...
	'BackgroundColor' ,[0.8 0.8 0.8],...
	'Enable','on',...
	'Tag','SortSubset');
	h1 = uicontrol('Parent',hfig, ...
	'Units','points', ...
	'Position',[30 240 82 29], ...
	'String','Sort All', ...
	'Callback','DoMultiChanFunctions SortAll',...
	'BackgroundColor' ,[1 0.5 0.5],...
	'Enable','on',...
	'Tag','SortAll');
	numsnips=0;
	for f=1:nfiles
		if (size(sptimes{f},2)>0)
			numsnips=numsnips+size(sptimes{f},2);
		end
	end
	h1 = uicontrol('Parent',hfig, ...
	'Units','points', ...
	'BackgroundColor',[1 1 1], ...
	'Position',[140 265 65 21], ...
	'String',g.subsetnum, ...
	'Style','edit', ...
	'Tag','NumSortSnips',...
	'Callback','DoMultiChanFunctions SortSubset');
	
	h1 = uicontrol('Parent',hfig, ...
	'Units','points', ...
	'HorizontalAlignment','left', ...
	'Position',[130 243 100 20], ...
	'String',['of ' num2str(numsnips) ' spikes'], ...
	'Style','text', ...
	'Tag','StaticText1');
	h1 = uicontrol('Parent',hfig, ...
	'Units','points', ...
	'Position',[30 80 82 29], ...
	'String','Cluster', ...
	'Callback','DoMultiChanFunctions Cluster',...
	'Enable','off',...
	'Tag','ClusterButton');
	hdeffltbox = uicontrol('Parent',gcf, ...
	'Units','points', ...
	'Position',[30 10 111 25], ...
	'String','Use default filters', ...
	'Style','checkbox', ...
	'Callback','DoMultiChanFunctions DefFiltBox',...
	'Tag','DefaultFiltersBox', ...
	'Value',1);
	h1 = uicontrol('Parent',hfig, ...
	'Units','points', ...
	'Position',[200 10 112 29], ...
	'String','Done Unassigned', ...
	'Callback','DoMultiChanFunctions DoneUnassigned',...
	'Tag','UnassignedButton');
	h1 = uicontrol('Parent',hfig, ...
	'Units','points', ...
	'HorizontalAlignment','right', ...
	'Position',[120 70 50 20], ...
	'String','block size', ...
	'Style','text', ...
	'Tag','StaticText1');
	hdispsnipsbox = uicontrol('Parent',gcf, ...
	'Units','points', ...
	'Position',[859 485 80 19], ...
	'String','Show spikes', ...
	'Style','checkbox', ...
	'Callback','DoMultiChanFunctions dispsnipsbox',...
	'Tag','dispsnipsbox', ...
	'Value',0);
	h1 = uicontrol('Parent',hfig, ...
	'Units','points', ...
	'HorizontalAlignment','left', ...
	'Position',[877 468 80 19], ...
	'String','from all files', ...
	'Style','text', ...
	'Tag','StaticText3');
	numsnips=100*(ceil((1+numsnips)/100));
	h1 = uicontrol('Parent',hfig, ...
	'Units','points', ...
	'BackgroundColor',[1 1 1], ...
	'Position',[180 70 61 21], ...
	'String',num2str(numsnips), ...
	'Style','edit', ...
	'Tag','BlockSize');
	h1 = uicontrol('Parent',hfig, ...
	'Units','points', ...
	'Position',[859 355 120 25], ...
	'String','Store in memory', ...
	'Callback','DoMultiChanFunctions Storeinmem',...
	'BackgroundColor' ,[0.8 0.8 0.8],...
	'Enable','on',...
	'Tag','Storeinmem');
end
h1 = uicontrol('Parent',hfig, ...
'Units','points', ...
'BackgroundColor',[1 1 1], ...
'HorizontalAlignment','right', ...
'Position',[901 507 40 20], ...
'String',num2str(params.dispsnips), ...
'Style','edit', ...
'Callback','DoMultiChanFunctions(''NumSnips'',gcbf)',...
'Tag','DispNumSnips');
h1 = uicontrol('Parent',hfig, ...
'Units','points', ...
'HorizontalAlignment','left', ...
'Position',[859 415 25 15], ...
'String','Max:', ...
'Style','text', ...
'Tag','StaticText4');
h1 = uicontrol('Parent',hfig, ...
'Units','points', ...
'BackgroundColor',[1 1 1], ...
'HorizontalAlignment','right', ...
'Position',[886 413 39 20], ...
'String',num2str(params.ACTime), ...
'Style','edit', ...
'Callback','DoMultiChanFunctions(''AutoCorrTime'',gcbf)',...
'Tag','ACTime');
h1 = uicontrol('Parent',hfig, ...
'Units','points', ...
'Position',[925 417 12 13], ...
'String','s', ...
'Style','text', ...
'Tag','StaticText4');

hctext(1) = uicontrol('Parent',hfig, ...
'Units','points', ...
'Position',[15 300 106 20], ...
'String','Unassigned: ', ...
'Style','text', ...
'Tag','StaticText2');
for i = 1:6
	left = 150+(i-1)*120;
	pos = [left 300 106 20];
	hctext(i+1) = uicontrol('Parent',hfig, ...
	'Units','points', ...
	'Position',pos, ...
	'String',sprintf('%d: 0',i), ...
	'Style','text', ...
	'Tag','ClusterText');
end

h1 = uicontrol('Parent',hfig, ...
'Units','points', ...
'Position',[30 40 82 29], ...
'String','MultiD Cluster', ...
'Callback','DoMultiChanFunctions MultiCluster',...
'Enable','on',...
'Tag','ClusterButton');
h1 = uicontrol('Parent',hfig, ...
'Units','points', ...
'Position',[630 90 82 29], ...
'String','CrossCorr', ...
'Callback','DoMultiChanFunctions CrossCorr',...
'Tag','CCButton');
h1 = uicontrol('Parent',hfig, ...
'Units','points', ...
'Position',[740 90 82 29], ...
'String','Join', ...
'Callback','DoMultiChanFunctions Join',...
'Tag','JoinButton');
h1 = uicontrol('Parent',hfig, ...
'Units','points', ...
'Position',[850 90 82 29], ...
'String','Full recording', ...
'Callback','DoMultiChanFunctions Recon',...
'Tag','ReconButton');
h1 = uicontrol('Parent',hfig, ...
'Units','points', ...
'Position',[630 45 82 29], ...
'String','Clear', ...
'Callback','DoMultiChanFunctions Clear',...
'Tag','ClearButton');
h1 = uicontrol('Parent',hfig, ...
'Units','points', ...
'Position',[630 0 82 29], ...
'String','Crosstalk', ...
'Callback','DoMultiChanFunctions Crosstalk',...
'Tag','CTButton');
%h1 = uicontrol('Parent',hfig, ...
%	'Units','points', ...
%	'Position',[740 0 95 29], ...
%	'String','Plot by autocorr', ...
%	'Callback','DoMultiChanFunctions Sep',...
%	'Tag','SepButton');
h1 = uicontrol('Parent',hfig, ...
'Units','points', ...
'Position',[740 45 82 29], ...
'String','Cancel', ...
'Callback','DoMultiChanFunctions Cancel',...
'Tag','CancelButton');
h1 = uicontrol('Parent',hfig, ...
'Units','points', ...
'Position',[850 45 82 29], ...
'String','Done', ...
'Callback','DoMultiChanFunctions Done',...
'Tag','DoneButton');
set(h1,'Enable','off');
h1 = uicontrol('Parent',hfig, ...
'Units','points', ...
'Position',[400 570 300 16], ...
'String',sprintf('Channels %s',num2str(sortchannels)), ...
'Style','text', ...
'Tag','ChannelNumberText');
h1 = axes('Parent',hfig, ...
'Units','pixels', ...
'CameraUpVector',[0 1 0], ...
'Color',[1 1 1], ...
'Position',[371 31 230 133], ...
'Tag','SpikesPerFile', ...
'XColor',[0 0 0], ...
'YColor',[0 0 0], ...
'ZColor',[0 0 0]);
hctlist = uicontrol('Parent',hfig, ...
'Units','points', ...
'HorizontalAlignment','left', ...
'Position',[620 120 150 40], ...
'String','Cross talk:', ...
'Style','text', ...
'Tag','StaticText1');
ylabel('# spikes/file');

% Set the data that the callbacks will need
if (~g.pwflag)
	set(hdeffltbox,'Enable','on');
	setappdata(hfig,'snipsize',g.sniprange(2)-g.sniprange(1)+1);
	setappdata(hfig,'nfiles',size(g.spikefiles,2));
else
	setappdata (hfig,'snipsize',30);
	setappdata (hfig,'nfiles',1);
end
setappdata(hfig,'params',params);
setappdata(hfig,'sortchannels',sortchannels);
setappdata(hfig,'chindices',chindices);
setappdata(hfig,'haxc',haxc);
setappdata(hfig,'hctext',hctext);
setappdata(hfig,'hctlist',hctlist);
setappdata(hfig,'nsnips',g.nsnips(chindices,:));
handles=getappdata(hmain,'handles');
handles.ctwin=-1;
setappdata(hfig,'handles',handles);
setappdata(hfig,'t',sptimes);
for fnum= 1:nfiles
	clflindxall{fnum} =1:size(sptimes{fnum},2);
end
setappdata(hfig,'clflindxall',clflindxall);
clflindxsub=getsubset(clflindxall,g.subsetnum);
setappdata(hfig,'clflindxsub',clflindxsub);
setappdata(hfig,'Sortstatus',1);
clflindx=clflindxall;
setappdata(hfig,'clflindx',clflindx);
setappdata(hfig,'Storestatus',0);
setappdata(hfig,'spindx',spindx);
setappdata(hfig,'updatevector',1);
setappdata(hfig,'clustmode',0);
setappdata(hfig,'rectime',rectime);
set (hfig,'CloseRequestFcn','') %Can't close with top-left window button
display.snips=cell(3,7);
display.corr.n=cell(3,7);
display.corr.x=cell(3,7);
display.hist.n=cell(3,7);
display.hist.x=cell(3,7);
updatearr(1:3,2:7)=-1;
updatearr(1:3,1)=0;
setappdata (hfig,'updatearr',updatearr);
setappdata(hfig,'dispsnipsallfiles',0)
setappdata (hfig,'display',display);
DoMultiChanFunctions('DefFiltBox',hfig);
set(haxc(:,1),'Selected','on');	% Start with the unassigned cluster selected
DoMultiChanFunctions('UpdateDisplay',hfig);
if nargout > 0, fig = hfig; end
DoMultiChanFunctions('Cluster',hfig);
