function fig = Cluster(x,y,polygons,clustnums)
% Cluster: Draw polygons around clusters in a scatter plot
% fig = Cluster(x,y)
%	x,y are the coordinates of the points
%	fig is the handle of the figure
%  Check to see if the figure's UserData has been set to "done"
%	(using waitfor) to use the results from clustering.
%  The polygons are stored in the figure's user property named "polygons,"
%	and cluster membership may be computed using the function ComputeMembership
%
% fig = Cluster(x,y,polygons,clustnums)
%	This form allows you to start with an initial set of polygons & cluster #s.
%	If polygons is present but clustnums is absent, default cluster numbers
%	are assigned. The "Clear" button is replaced by a "Revert" button,
%	restoring the original state.
hfig = figure('Units','points', ...
	'Color',[0.8 0.8 0.8], ...
	'Position',[255 295 511 422], ...
	'KeyPressFcn','ClusterFunctions KeyTrap', ...
	'Tag','Fig1');
hax = axes('Parent',hfig, ...
	'Units','pixels', ...
	'CameraUpVector',[0 1 0], ...
	'Color',[1 1 1], ...
	'Position',[38 75 357 293], ...
	'Tag','ClustAx', ...
	'ButtonDownFcn','ClusterFunctions DoPolygon', ...
	'XColor',[0 0 0], ...
	'YColor',[0 0 0], ...
	'ZColor',[0 0 0]);
h1 = uicontrol('Parent',hfig, ...
	'Units','points', ...
	'Position',[412 187 76 30], ...
	'String','Done',...
	'Callback','ClusterFunctions Done', ...
	'Tag','DoneButton');
if (nargin < 3)
	polygons = {};
	clustnums = [];
end
if (nargin == 3)
	clustnums = 1:length(polygons);
end
h1 = uicontrol('Parent',hfig, ...
	'Units','points', ...
	'Position',[412 132 76 30], ...
	'String','Clear',...
	'Callback','ClusterFunctions Clear', ...
	'Tag','ClearButton');
if (nargin == 4)
	set(h1,'String','Revert','Callback','ClusterFunctions Revert');
	setappdata(hfig,'clustnums0',clustnums);
	setappdata(hfig,'polygons0',polygons);
end
h1 = uicontrol('Parent',hfig, ...
	'Units','points', ...
	'Position',[412 74 76 30], ...
	'String','Cancel',...
	'Callback','ClusterFunctions Cancel', ...
	'Tag','CancelButton');
h1 = uicontrol('Parent',hfig, ...
	'Units','points', ...
	'Callback','ClusterFunctions ScatterPlot', ...
	'Position',[37 19.5 76 30], ...
	'String','Density', ...
	'Tag','ScatDensButton');
xrange = max(x)-min(x);
yrange = max(y)-min(y);
range = min(xrange,yrange);
if (range< 1)
	range = 1;
end
h1 = uicontrol('Parent',hfig, ...
	'Units','points', ...
	'Position',[137 22.5 142 24], ...
	'Style','slider', ...
	'Min',log(range/100), ...
	'Max',log(range/2), ...
	'Value',log(range/10), ...
	'Callback','ClusterFunctions DensityPlot', ...
	'Tag','Slider');
h1 = uicontrol('Parent',hfig, ...
	'Units','points', ...
	'Position',[153 7 113 15], ...
	'String','Bin width', ...
	'Style','text', ...
	'Tag','BinWidthText');
h1 = uicontrol('Parent',hfig, ...
	'Units','points', ...
	'Callback','ClusterFunctions ShowMembership', ...
	'Position',[318 19.5 76 30], ...
	'String','Show Clusts', ...
	'Tag','ShowClustsButton');
setappdata(hfig,'x',x);
setappdata(hfig,'y',y);
setappdata(hfig,'clustnums',clustnums);
setappdata(hfig,'polygons',polygons);
setappdata(hfig,'hploygons',[]);
setappdata(hfig,'hclustpts',[]);
setappdata(hfig,'selectflag',[]);
setappdata(hfig,'membership',zeros(size(x)));
setappdata(hfig,'SelCb','ClusterFunctions SelectCluster');
ClusterFunctions('ScatterPlot',hfig);
if nargout > 0, fig = hfig; end
