function fig = Record()

load Record

gainstr = {'±10V','±5V','±2.5V','±1V','±500mV','±200mV','±100mV','±50mV'};
trigstr = {'In','Out'};
savestr = {'Don''t save','Save'};

col1 = 11;
col2 = 85;
col3 = 165;
col4 = 265;
col5 = 370;
col6 = 470;
% The figure
h0 = figure('Units','points', ...
	'Color',[0.8 0.8 0.8], ...
	'Colormap',mat0, ...
	'Position',[15 350 560 375], ...
	'Name','Recording Parameters', ...
	'NumberTitle','off', ...
	'HandleVisibility','callback',...
	'Tag','RecParamWindow');
% Channels
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'Position',[col1 340 45 13], ...
	'String','Channels', ...
	'Style','text', ...
	'HorizontalAlignment','left', ...
	'Tag','StaticText1');
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[1 1 1], ...
	'Position',[col2 336 276 21], ...
	'String','0:63', ...
	'Style','edit', ...
	'HorizontalAlignment','left', ...
	'Tag','ChannelString');
%Scan rate
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'Position',[col1 307 85 13], ...
	'String','Scans/sec', ...
	'Style','text', ...
	'HorizontalAlignment','left', ...
	'Tag','StaticText2');
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[1 1 1], ...
	'Position',[col2 303 52 21], ...
	'String','10000', ...
	'Style','edit', ...
	'HorizontalAlignment','right', ...
	'Tag','ScanRate');
% Recording time
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'Position',[col3 307 95 13], ...
	'String','Recording time (s)', ...
	'Style','text', ...
	'HorizontalAlignment','left', ...
	'Tag','StaticText4');
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[1 1 1], ...
	'Position',[col4 303 69 21], ...
	'String','300', ...
	'Style','edit', ...
	'HorizontalAlignment','right', ...
	'Tag','RecordingTime');
% Buffer size
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'Position',[col5 307 100 13], ...
	'String','Buffer size (scans)', ...
	'Style','text', ...
	'HorizontalAlignment','left', ...
	'Tag','StaticText5');
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[1 1 1], ...
	'Position',[col6 303 57 21], ...
	'String','50000', ...
	'Style','edit', ...
	'HorizontalAlignment','right', ...
	'Tag','BufferSize');
% Trigger
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'Position',[col1 261 41 14], ...
	'String','Trigger', ...
	'Style','text', ...
	'HorizontalAlignment','left', ...
	'Tag','StaticText6');
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'Position',[col2 254 61 22], ...
	'String',trigstr, ...
	'Style','popupmenu', ...
	'Tag','Trigger', ...
	'Value',2);
% Recording range
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'Position',[col3 261 91 14], ...
	'String','Recording range', ...
	'Style','text', ...
	'HorizontalAlignment','left', ...
	'Tag','StaticText3');
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'Position',[col4 254 85 22], ...
	'String',gainstr, ...
	'Style','popupmenu', ...
	'Tag','RecordingGain', ...
	'Value',2);
% Plotting range
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'Position',[col5 261 76 14], ...
	'String','Plotting range', ...
	'Style','text', ...
	'HorizontalAlignment','left', ...
	'Tag','StaticText3');
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'Position',[col6 254 85 22], ...
	'String',gainstr, ...
	'Style','popupmenu', ...
	'Tag','PlottingGain', ...
	'Value',2);
% Save popup
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'Position',[col2 178 100 22], ...
	'String',savestr, ...
	'Style','popupmenu', ...
	'Tag','SaveMode', ...
	'Callback','RecParamCallback savemode', ...
	'Value',2);
%% Radiobuttons: save
%h1 = uicontrol('Parent',h0, ...
%	'Units','points', ...
%	'Position',[236 178 29 15], ...
%	'String','Save', ...
%	'Style','text', ...
%	'Tag','StaticText7', ...
%	'Value',1);
%h1 = uicontrol('Parent',h0, ...
%	'Units','points', ...
%	'Position',[215 178 19 19], ...
%	'Style','radiobutton', ...
%	'Max',1,'Min',0, ...
%	'Value',1, ...
%	'Callback','RecParamCallback savebutton', ...
%	'Tag','save');
%%    and don't save
%h1 = uicontrol('Parent',h0, ...
%	'Units','points', ...
%	'Position',[96 178 60 15], ...
%	'String','Don''t save', ...
%	'Style','text', ...
%	'Tag','StaticText7');
%h1 = uicontrol('Parent',h0, ...
%	'Units','points', ...
%	'Position',[77 178 19 19], ...
%	'Style','radiobutton', ...
%	'Max',1,'Min',0, ...
%	'Value',0, ...
%	'Callback','RecParamCallback dontsavebutton', ...
%	'Tag','dontsave');
% Header text
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'Position',[col1 154 64 13], ...
	'String','Header text', ...
	'Style','text', ...
	'HorizontalAlignment','left', ...
	'Tag','usrheaderTxt');
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[1 1 1], ...
	'Position',[col2 110 470 61], ...
	'Style','edit', ...
	'Tag','usrheader', ...
	'HorizontalAlignment','left', ...
	'Max',2,'Min',0);		% Accept multi-line input
% filename
%h1 = uicontrol('Parent',h0, ...
%	'Units','points', ...
%	'Position',[13 74 49 13], ...
%	'String','Filename', ...
%	'Style','text', ...
%	'Tag','basenameTxt');
%h1 = uicontrol('Parent',h0, ...
%	'Units','points', ...
%	'BackgroundColor',[1 1 1], ...
%	'Position',[78 70 164 21], ...
%	'Style','edit', ...
%	'Tag','basename');
% Cancel button
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'Position',[col6-90 23 76 30], ...
	'String','Cancel', ...
	'Callback','RecParamCallback CancelButton', ...
	'Tag','CancelButton');
% OK button
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'Position',[col6 23 76 30], ...
	'String','OK', ...
	'Callback','RecParamCallback OKButton', ...
	'Tag','OKButton');
if nargout > 0, fig = h0; end
set(0,'DefaultPatchEdgeColor','b') 
